name: Reclutamiento de Agente

on: push

jobs:
    reporte-de-reclutamiento:
        runs-on: ubuntu-latest

        steps:
            - name: El agente se presenta
              run: echo "Soy Lex Luthor, y el líder de la Legión del Mal"
