name: Comunicador de la Legión

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "¿Qué villano envía el mensaje?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Magneto
          - Joker
          - Mystique
          - Brainiac

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

