name: Comunicador de la Legión

on:
  workflow_dispatch:
    inputs:
      villano:
        description: '¿Qué villano envía el mensaje?'
        required: true
        type: choice
        options:
          - Lex Luthor
          - Magneto
          - Joker
          - Mystique
          - Brainiac
      mensaje:
        description: 'Mensaje para el consejo'
        required: true
        default: 'La misión fue un éxito'

      prioridad:
        description: 'Nivel de prioridad'
        required: true
        type: choice
        options:
          - 🟢 Normal
          - 🟡 Alta
          - 🔴 Crítica

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir inputs
        run: |
          echo "Inputs: "
          echo ""
          echo "Villano: ${{ inputs.villano }}"
          echo "Nivel: ${{ inputs.prioridad }}"
          echo "Mensaje: ${{ inputs.mensaje }}"
